name: Build and test (allValidatorsWithInterface)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./allValidatorsWithInterface/
      run: chmod +x gradlew
    - name: Build with Gradle
      working-directory: ./allValidatorsWithInterface/
      run: ./gradlew build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./allValidatorsWithInterface/
      run: chmod +x gradlew
    - name: Build with Gradle (JDK 11)
      working-directory: ./allValidatorsWithInterface/
      run: ./gradlew test
      
  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      working-directory: ./allValidatorsWithInterface/
      run: chmod +x gradlew
    - name: Run Test Coverage
      working-directory: ./allValidatorsWithInterface/
      run: ./gradlew jacocoTestReport
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        files: ./allValidatorsWithInterface/build/reports/jacoco/test/jacocoTestReport.xml
