name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        working-directory: ./allValidatorsWithInterface/
        run: chmod +x gradlew
        
      - name: Run Tests
        working-directory: ./allValidatorsWithInterface/
        run: ./gradlew test

      - name: Run Test Coverage
        working-directory: ./allValidatorsWithInterface/
        run: ./gradlew jacocoTestReport
        
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
